### ISSUE TITLE
Display a progress-bar when downloading prebuilt Nodes

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [nodenv/node-build#292] opened 2017-07-22 10:20 UTC
When I execute `nodenv install 8.1.4`, I get something like this:

    Downloading node-v8.1.4-darwin-x64.tar.gz...
    -> https://nodejs.org/dist/v8.1.4/node-v8.1.4-darwin-x64.tar.gz

When on a slow WiFi or VPN, it can sit there for … quite a while. Exposing `aria2c`'s progress bar or something like that would really improve the UX!

**Comment by jasonkarns** [comment] 2017-09-07 14:05
Agree! but closing as a dupe of https://github.com/rbenv/ruby-build/pull/536

Since progress-bars are a feature for both node-build and ruby-build, I would prefer they land in upstream first.

**Closed by jasonkarns** 2017-09-07 14:05 UTC
